apiVersion: v1
kind: Namespace
metadata:
  name:  app-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-test-deployment
  namespace: app-test
spec:
  selector:
    matchLabels:
      app: app-test-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: app-test-pod
    spec:
      containers:
      - name: app-test-pod
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "0.1"
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: app-test-service
  namespace: app-test
spec:
  selector:
    app: app-test-pod
  ports:
  - port: 8080
    name: http
    targetPort: 80
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "letsencrypt-prod"
  namespace: app-test
spec:
  acme:
    email: alexanderdolgosheev@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: example-issuer-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-test-ingress
  namespace: app-test
  labels:
    name: app-test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - weather.paradox-server.ru
    secretName: weather-paradox-server-tls
  rules:
  - host: weather.paradox-server.ru
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app-test-service
            port: 
              name: http
  ingressClassName: nginx